### ISSUE TITLE
时好时坏，错误显示connect ETIMEDOUT 74.125.204.113:80

### ISSUE THREAD

**Issue by yinguangluoren** [lqqyt2423/wechat_spider#21]
时好时坏， 有时候可以正常爬去， 有时候就是公众号页面点不开，  开启了 onError事件打印错误 总显示如下错误

 { Error: connect ETIMEDOUT 74.125.204.113:80
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '74.125.204.113',
  port: 80 }

请问是哪里出现的问题呢

**Comment by yinguangluoren** [comment]
似乎不是代码问题， 使用的是海马模拟器， 断开代理之后依旧无法点开公众号
