### ISSUE TITLE
手机证书安装后，代理8104端口，公众号文章内容打不开

### ISSUE THREAD

**Issue by alangong114** [lqqyt2423/wechat_spider#32]
微信新版本 7.0.3
Andriod：9.0.4 
配置好代理后，打不开公众号文章历史页面，点击公众号内容，也也显示白屏
查看anyproxy 日志，提示连接被重置
Error: read ECONNRESET
是不是微信版太新造成的，项目非常棒，谢谢分享

> 2019-04-26T03:28:30.126713875Z [AnyProxy Log][2019-04-26 03:28:30]: received request to: POST res.imtt.qq.com/qbprobe/netprobe.txt?t=1556249309170
2019-04-26T03:28:30.136214045Z [AnyProxy Log][2019-04-26 03:28:30]: received request to: POST res.imtt.qq.com/qbprobe/netprobe.txt?t=1556249309114
2019-04-26T03:28:32.643456972Z [AnyProxy Log][2019-04-26 03:28:32]: received https CONNECT request play.googleapis.com
2019-04-26T03:28:32.681006912Z [AnyProxy Log][2019-04-26 03:28:32]: will forward to local https server
2019-04-26T03:28:33.288088594Z [AnyProxy Log][2019-04-26 03:28:33]: [internal https]proxy server for play.googleapis.com established
2019-04-26T03:28:33.318730911Z [AnyProxy ERROR][2019-04-26 03:28:33]: Error: read ECONNRESET
2019-04-26T03:28:38.803598413Z [AnyProxy ERROR][2019-04-26 03:28:38]: Error: connect ETIMEDOUT 203.119.215.254:35667
2019-04-26T03:28:42.781410959Z [AnyProxy Log][2019-04-26 03:28:42]: received https CONNECT request mobilenetworkscoring-pa.googleapis.com
2019-04-26T03:28:42.809838445Z [AnyProxy Log][2019-04-26 03:28:42]: will forward to local https server
2019-04-26T03:28:42.809873751Z [AnyProxy Log][2019-04-26 03:28:42]: [internal https]proxy server for mobilenetworkscoring-pa.googleapis.com established
2019-04-26T03:28:42.831666686Z [AnyProxy ERROR][2019-04-26 03:28:42]: Error: read ECONNRESET
2019-04-26T03:28:59.606489881Z [AnyProxy Log][2019-04-26 03:28:59]: received request to: GET www.noisyfox.cn/generate_204
2019-04-26T03:28:59.606519663Z [AnyProxy Log][2019-04-26 03:28:59]: received request to: GET conn1.oppomobile.com/generate_204
2019-04-26T03:28:59.606526340Z [AnyProxy Log][2019-04-26 03:28:59]: received request to: GET developers.google.cn/generate_204
2019-04-26T03:29:00.160849413Z [AnyProxy Log][2019-04-26 03:29:00]: received request to: POST res.imtt.qq.com/qbprobe/netprobe.txt?t=1556249339212
2019-04-26T03:29:01.247247368Z [AnyProxy Log][2019-04-26 03:29:01]: received request to: POST res.imtt.qq.com/qbprobe/netprobe.txt?t=1556249340272
2019-04-26T03:29:01.256491263Z [AnyProxy Log][2019-04-26 03:29:01]: received request to: POST res.imtt.qq.com/qbprobe/netprobe.txt?t=1556249340267
2019-04-26T03:29:01.256522681Z [AnyProxy Log][2019-04-26 03:29:01]: received request to: POST res.imtt.qq.com/qbprobe/netprobe.txt?t=1556249340273
2019-04-26T03:29:06.828507316Z [AnyProxy Log][2019-04-26 03:29:06]: received https CONNECT request mobilenetworkscoring-pa.googleapis.com
2019-04-26T03:29:06.857067239Z [AnyProxy Log][2019-04-26 03:29:06]: will forward to local https server
2019-04-26T03:29:06.857099576Z [AnyProxy Log][2019-04-26 03:29:06]: [internal https]proxy server for mobilenetworkscoring-pa.googleapis.com established
2019-04-26T03:29:06.898038874Z [AnyProxy ERROR][2019-04-26 03:29:06]: Error: read ECONNRESET
2019-04-26T03:29:13.832568637Z [AnyProxy Log][2019-04-26 03:29:13]: received https CONNECT request mp.weixin.qq.com
2019-04-26T03:29:13.841724915Z [AnyProxy Log][2019-04-26 03:29:13]: will forward to local https server
2019-04-26T03:29:13.841748897Z [AnyProxy Log][2019-04-26 03:29:13]: [internal https]proxy server for mp.weixin.qq.com established
2019-04-26T03:29:14.032441032Z [AnyProxy Log][2019-04-26 03:29:14]: received request to: GET wechatfe.github.io/vconsole/lib/vconsole.min.js?v=3.0.0.0
2019-04-26T03:29:31.244230881Z [AnyProxy Log][2019-04-26 03:29:31]: received request to: POST res.imtt.qq.com/qbprobe/netprobe.txt?t=1556249370291
2019-04-26T03:29:31.351350905Z [AnyProxy Log][2019-04-26 03:29:31]: received request to: POST res.imtt.qq.com/qbprobe/netprobe.txt?t=1556249370400
2019-04-26T03:30:03.796142529Z [AnyProxy ERROR][2019-04-26 03:30:03]: Error: connect ETIMEDOUT 203.119.215.254:35667
2019-04-26T03:30:03.796183261Z [AnyProxy ERROR][2019-04-26 03:30:03]: Error: This socket is closed
2019-04-26T03:30:03.796189790Z Error: This socket is closed
2019-04-26T03:30:03.796194141Z     at Socket._writeGeneric (net.js:733:18)
2019-04-26T03:30:03.796198075Z     at Socket._write (net.js:787:8)
2019-04-26T03:30:03.796201864Z     at doWrite (_stream_writable.js:396:12)
2019-04-26T03:30:03.796205651Z     at writeOrBuffer (_stream_writable.js:382:5)
2019-04-26T03:30:03.796209437Z     at Socket.Writable.write (_stream_writable.js:290:11)
2019-04-26T03:30:03.796213253Z     at Socket.write (net.js:711:40)
2019-04-26T03:30:03.796216994Z     at /app/node_modules/anyproxy/lib/requestHandler.js:686:19
2019-04-26T03:30:03.796220846Z     at Generator.next (<anonymous>)
2019-04-26T03:30:03.796225191Z     at onFulfilled (/app/node_modules/co/index.js:65:19)
2019-04-26T03:30:03.796229036Z     at <anonymous>
2019-04-26T03:30:03.796233008Z     at process._tickCallback (internal/process/next_tick.js:189:7)
2019-04-26T03:30:05.409512632Z [AnyProxy Log][2019-04-26 03:30:05]: received https CONNECT request mobilenetworkscoring-pa.googleapis.com
2019-04-26T03:30:05.425946557Z [AnyProxy Log][2019-04-26 03:30:05]: will forward to local https server
2019-04-26T03:30:05.425991461Z [AnyProxy Log][2019-04-26 03:30:05]: [internal https]proxy server for mobilenetworkscoring-pa.googleapis.com established
2019-04-26T03:30:05.465077395Z [AnyProxy ERROR][2019-04-26 03:30:05]: Error: read ECONNRESET
2019-04-26T03:30:06.422225622Z [AnyProxy Log][2019-04-26 03:30:06]: received request to: POST sqimg.qq.com/qq_product_operations/nettest/index2.html?r=34359&mType=netdetect
2019-04-26T03:30:06.422266199Z [AnyProxy Log][2019-04-26 03:30:06]: received request to: POST sqimg.qq.com/qq_product_operations/nettest/index.html?r=57236&mType=netdetect
2019-04-26T03:30:12.931027060Z [AnyProxy Log][2019-04-26 03:30:12]: received request to: POST oth.eve.mdt.qq.com:8080/analytics/upload?rid=108774cc25ee75f0&sid=0bb20be38c36f8938e1f782acc3f051d
2019-04-26T03:30:14.179052470Z [AnyProxy Log][2019-04-26 03:30:14]: received https CONNECT request telemetry-in.battle.net
2019-04-26T03:30:14.191936241Z [AnyProxy Log][2019-04-26 03:30:14]: will forward to local https server
2019-04-26T03:30:14.515154665Z [AnyProxy Log][2019-04-26 03:30:14]: [internal https]proxy server for telemetry-in.battle.net established
2019-04-26T03:30:14.533253313Z [AnyProxy ERROR][2019-04-26 03:30:14]: Error: read ECONNRESET
2019-04-26T03:30:21.454988512Z [AnyProxy Log][2019-04-26 03:30:21]: received request to: POST oth.eve.mdt.qq.com:8080/analytics/upload?rid=8e3aad721715f234&sid=93c882e5f255ac9ef2e4b063fbbc6167
2019-04-26T03:30:55.501331602Z [AnyProxy Log][2019-04-26 03:30:55]: received https CONNECT request mobilenetworkscoring-pa.googleapis.com
2019-04-26T03:30:55.510262166Z [AnyProxy Log][2019-04-26 03:30:55]: will forward to local https server
2019-04-26T03:30:55.510299666Z [AnyProxy Log][2019-04-26 03:30:55]: [internal https]proxy server for mobilenetworkscoring-pa.googleapis.com established
2019-04-26T03:30:55.520385873Z [AnyProxy ERROR][2019-04-26 03:30:55]: Error: read ECONNRESET
2019-04-26T03:30:55.822799045Z [AnyProxy Log][2019-04-26 03:30:55]: received request to: GET www.google.cn/generate_204
2019-04-26T03:30:55.822832311Z [AnyProxy Log][2019-04-26 03:30:55]: received request to: GET www.noisyfox.cn/generate_204
2019-04-26T03:30:55.830259307Z [AnyProxy Log][2019-04-26 03:30:55]: received request to: GET conn2.oppomobile.com/generate_204
2019-04-26T03:30:56.376093723Z [AnyProxy Log][2019-04-26 03:30:56]: received https CONNECT request mobilenetworkscoring-pa.googleapis.com
2019-04-26T03:30:56.384066650Z [AnyProxy Log][2019-04-26 03:30:56]: received https CONNECT request android.clients.google.com
2019-04-26T03:30:56.393705227Z [AnyProxy Log][2019-04-26 03:30:56]: will forward to local https server
2019-04-26T03:30:56.393738585Z [AnyProxy Log][2019-04-26 03:30:56]: [internal https]proxy server for mobilenetworkscoring-pa.googleapis.com established
2019-04-26T03:30:56.411514634Z [AnyProxy ERROR][2019-04-26 03:30:56]: Error: read ECONNRESET
2019-04-26T03:30:56.432187735Z [AnyProxy Log][2019-04-26 03:30:56]: will forward to local https server
2019-04-26T03:30:56.623831916Z [AnyProxy Log][2019-04-26 03:30:56]: [internal https]proxy server for android.clients.google.com established
2019-04-26T03:30:56.641300337Z [AnyProxy ERROR][2019-04-26 03:30:56]: Error: read ECONNRESET
2019-04-26T03:31:53.926218997Z [AnyProxy Log][2019-04-26 03:31:53]: received request to: POST mazu.3g.qq.com/
2019-04-26T03:31:56.899228291Z [AnyProxy Log][2019-04-26 03:31:56]: received request to: POST log.tbs.qq.com/ajax?c=pu&tk=4b64865480e241c1957255c83be0f7d0a009f5d6eff6982e319aeef9467dd4596e25f009b49e830ca4130a91e1adbea0
2019-04-26T03:32:08.938755493Z [AnyProxy Log][2019-04-26 03:32:08]: received https CONNECT request android.clients.google.com
2019-04-26T03:32:08.949924088Z [AnyProxy Log][2019-04-26 03:32:08]: will forward to local https server
2019-04-26T03:32:08.949957057Z [AnyProxy Log][2019-04-26 03:32:08]: [internal https]proxy server for android.clients.google.com established
2019-04-26T03:32:08.962632604Z [AnyProxy ERROR][2019-04-26 03:32:08]: Error: read ECONNRESET
2019-04-26T03:32:28.949789680Z [AnyProxy Log][2019-04-26 03:32:28]: received https CONNECT request mobilenetworkscoring-pa.googleapis.com
2019-04-26T03:32:28.964018981Z [AnyProxy Log][2019-04-26 03:32:28]: will forward to local https server
2019-04-26T03:32:28.975869201Z [AnyProxy Log][2019-04-26 03:32:28]: [internal https]proxy server for mobilenetworkscoring-pa.googleapis.com established
2019-04-26T03:32:33.996770666Z [AnyProxy Log][2019-04-26 03:32:33]: received https CONNECT request mobilenetworkscoring-pa.googleapis.com
2019-04-26T03:32:34.010786129Z [AnyProxy Log][2019-04-26 03:32:34]: will forward to local https server
2019-04-26T03:32:34.010818716Z [AnyProxy Log][2019-04-26 03:32:34]: [internal https]proxy server for mobilenetworkscoring-pa.googleapis.com established
2019-04-26T03:32:34.024616125Z [AnyProxy ERROR][2019-04-26 03:32:34]: Error: read ECONNRESET
2019-04-26T03:32:46.993967838Z [AnyProxy Log][2019-04-26 03:32:46]: received https CONNECT request android.googleapis.com
2019-04-26T03:32:47.015119922Z [AnyProxy Log][2019-04-26 03:32:47]: will forward to local https server
2019-04-26T03:32:47.280536925Z [AnyProxy Log][2019-04-26 03:32:47]: [internal https]proxy server for android.googleapis.com established
2019-04-26T03:32:51.128234734Z [AnyProxy Log][2019-04-26 03:32:51]: received request to: POST sqimg.qq.com/qq_product_operations/nettest/index2.html?r=64800&mType=netdetect
2019-04-26T03:32:51.128291808Z [AnyProxy Log][2019-04-26 03:32:51]: received request to: POST sqimg.qq.com/qq_product_operations/nettest/index.html?r=64800&mType=netdetect
2019-04-26T03:33:24.368909082Z [AnyProxy Log][2019-04-26 03:33:24]: received request to: GET developers.google.cn/generate_204
2019-04-26T03:33:24.368942632Z [AnyProxy Log][2019-04-26 03:33:24]: received request to: GET conn2.oppomobile.com/generate_204
2019-04-26T03:33:24.368949642Z [AnyProxy Log][2019-04-26 03:33:24]: received request to: GET www.noisyfox.cn/generate_204
2019-04-26T03:33:34.271459873Z [AnyProxy Log][2019-04-26 03:33:34]: received https CONNECT request mobilenetworkscoring-pa.googleapis.com
2019-04-26T03:33:34.282937695Z [AnyProxy Log][2019-04-26 03:33:34]: will forward to local https server
2019-04-26T03:33:34.282984689Z [AnyProxy Log][2019-04-26 03:33:34]: [internal https]proxy server for mobilenetworkscoring-pa.googleapis.com established
2019-04-26T03:33:58.326337120Z [AnyProxy Log][2019-04-26 03:33:58]: received https CONNECT request mobilenetworkscoring-pa.googleapis.com
2019-04-26T03:33:58.341699363Z [AnyProxy Log][2019-04-26 03:33:58]: will forward to local https server
2019-04-26T03:33:58.341736521Z [AnyProxy Log][2019-04-26 03:33:58]: [internal https]proxy server for mobilenetworkscoring-pa.googleapis.com established
2019-04-26T03:33:58.358426254Z [AnyProxy ERROR][2019-04-26 03:33:58]: Error: read ECONNRESET
2019-04-26T03:34:04.905472777Z [AnyProxy Log][2019-04-26 03:34:04]: received https CONNECT request android.googleapis.com
2019-04-26T03:34:04.932094469Z [AnyProxy Log][2019-04-26 03:34:04]: will forward to local https server
2019-04-26T03:34:04.932128075Z [AnyProxy Log][2019-04-26 03:34:04]: [internal https]proxy server for android.googleapis.com established
2019-04-26T03:34:04.943257364Z [AnyProxy ERROR][2019-04-26 03:34:04]: Error: read ECONNRESET

**Comment by 52Lau** [comment]
安卓微信现在强制更新了，本身安卓的微信，做采集的话，要低于7.0以下

**Comment by alangong114** [comment]
> 安卓微信现在强制更新了，本身安卓的微信，做采集的话，要低于7.0以下

嗯，6.x 版本的微信试过了，可以！ 谢谢非常棒，我现在想在上面加入一个发布到mysql的功能，请问在nodejs，server/index.js 里面直接引入mysql的库 会不会和monogo冲突？
